{
 "title": "Ambassador",
 "description": "Ambassador dashboard for Prometheus",
 "tags": [ "ambassador" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "listener_port", "label": "Listener port", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_2xx[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_3xx[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_4xx[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_listener_0_0_0_0_${listener_port}_http_ingress_http_downstream_rq_5xx[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Downstream Connections Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_listener_0_0_0_0_${listener_port}_downstream_cx_length_ms{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Downstream Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http1_total[1m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_http2_total[1m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum(increase(envoy_http_ingress_http_downstream_cx_websocket_total[1m]))",
     "legendFormat": "WebSocket"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "envoy_cluster_manager_active_clusters"
    }
   ]
  },
  { "title": "External Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "External Auth Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_cluster_ext_auth_upstream_rq_time{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_auth_upstream_rq_time{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_auth_upstream_rq_time{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "External Auth Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_auth_upstream_rq_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_auth_upstream_rq_cancelled[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_auth_upstream_rq_timeout[1m]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_auth_upstream_rq_pending_total[1m]))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_auth_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  { "title": "External Rate Limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "External Rate Limit Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_cluster_ext_ratelimit_upstream_rq_time{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_ratelimit_upstream_rq_time{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_ratelimit_upstream_rq_time{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "External Rate Limit Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_ratelimit_upstream_rq_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_ratelimit_upstream_rq_cancelled[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_ratelimit_upstream_rq_timeout[1m]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_ratelimit_upstream_rq_pending_total[1m]))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_ratelimit_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    }
   ]
  },
  { "title": "External Tracing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "External Tracing Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_cluster_ext_tracing_upstream_rq_time{quantile=\"0.5\"}",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_tracing_upstream_rq_time{quantile=\"0.9\"}",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "envoy_cluster_cluster_ext_tracing_upstream_rq_time{quantile=\"0.99\"}",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "External Tracing Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_tracing_upstream_rq_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_tracing_upstream_rq_cancelled[1m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_tracing_upstream_rq_timeout[1m]))",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_tracing_upstream_rq_pending_total[1m]))",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(increase(envoy_cluster_cluster_ext_tracing_upstream_rq_retry[1m]))",
     "legendFormat": "Retry"
    }
   ]
  }
 ]
}