{
 "title": "1 Node Exporter 0.16 0.17 for Prometheus",
 "description": "Node Exporter v0.17",
 "tags": [
  "Prometheus",
  "Node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(node_exporter_build_info{env='$env'},name)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(node_exporter_build_info{name='$name'},instance)"
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Load（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemFree_bytes{instance=~\"$node\"} - node_memory_Buffers_bytes{instance=~\"$node\"} - node_memory_Cached_bytes{instance=~\"$node\"}) / (node_memory_MemTotal_bytes{instance=~\"$node\"} )) * 100"
    }
   ]
  },
  {
   "title": "Node files allocated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Root FS available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Max used mount fs ($maxmount)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load Avarage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU  Load by mode",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} + node_memory_MemFree_bytes{instance=~\"$node\"})",
     "legendFormat": "MemUsed"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
     "legendFormat": "MemAvailable"
    }
   ]
  },
  {
   "title": "Disk R/W IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops", "label": "Read (-) / Write (+)  ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_reads_completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_writes_completed"
    }
   ]
  },
  {
   "title": "Disk R/W Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_read_bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_written_bytes"
    }
   ]
  },
  {
   "title": "Disk R/W Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Read (-) / Write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|lo'}[5m])*8",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|lo'}[5m])*8",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "TCP conn by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}